services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecomonitor-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ecomonitor-network

  api:
    image: ecomonitor-api:dev
    container_name: ecomonitor-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=MonitoramentoEnergeticoDB;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
    ports:
      - "8080:80"
    networks:
      - ecomonitor-network

volumes:
  sqlserver_data:

networks:
  ecomonitor-network:
    driver: bridge