name: EcoMonitor CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar API
        run: dotnet restore MonitoramentoEnergetico.csproj

      - name: Restaurar testes
        run: dotnet restore MonitoramentoEnergeticoAPI.Tests/MonitoramentoEnergeticoAPI.Tests.csproj

      - name: Compilar API
        run: dotnet build MonitoramentoEnergetico.csproj --no-restore --configuration Release

      - name: Executar testes
        run: dotnet test MonitoramentoEnergeticoAPI.Tests/MonitoramentoEnergeticoAPI.Tests.csproj --no-restore --configuration Release